### ISSUE TITLE
Change licence to LGPL v2.1 or MIT? Ask all contributors!

### ISSUE THREAD

**Issue by JonasSchaub** [FelixBaensch/MORTAR#28]

**Comment by FelixBaensch** [comment]
Could you please briefly summarize the differences and the advantage of the MIT license

**Comment by FelixBaensch** [comment]
Done a quick research:

- The MIT License (free) is a permissive free software license originating at the Massachusetts Institute of Technology (MIT) in the late 1980s. As a permissive license, it puts only very limited restriction on reuse and has, therefore, high license compatibility.
- The GNU General Public License (free) (GNU GPL or simply GPL) is a series of widely used free software licenses that guarantee end users the four freedoms to run, study, share, and modify the software BUT is otherwise restrictive which is why its only popular for Linux
- The GNU Lesser General Public License (LGPL) (free) is a free-software license published by the Free Software Foundation (FSF). The license allows developers and companies to use and integrate a software component released under the LGPL into their own (even proprietary) software without being required by the terms of a strong copyleft license to release the source code of their own components. However, any developer who modifies an LGPL-covered component is required to make their modified version available under the same LGPL license. This is an attempt to make the GPL type license a little bit more palatable but is still inferior to the MIT and BSD licenses.
- BSD licenses (free) are a family of permissive free software licenses, imposing minimal restrictions on the use and distribution of covered software. This is in contrast to copyleft licenses, which have share-alike requirements. The original BSD license was used for its namesake, the Berkeley Software Distribution (BSD), a Unix-like operating system. The original version has since been revised, and its descendants are referred to as modified BSD licenses. This is the most permissive license and most supportive of the concept of free open source software
- The Apache License is a permissive free software license written by the Apache Software Foundation (ASF). It allows users to use the software for any purpose, to distribute it, to modify it, and to distribute modified versions of the software under the terms of the license, without concern for royalties. The ASF and its projects release their software products under the Apache License. The license is also used by many non-ASF projects. This is also very permissive like the BSD license

(https://www.quora.com/Can-you-explain-the-difference-between-MIT-GPL-and-LGPL-licenses)

Therefore, I would prefer to change to MIT or BSD for further releases

**Comment by JonasSchaub** [comment]
> Therefore, I would prefer to change to MIT or BSD for further releases

I agree with this! And since we did not modify underlying packages that are licensed under LGPL (e.g. CDK), we should have no problem there, right?

**Comment by FelixBaensch** [comment]
If "modify" does not include "extend", I think we're fine.
I think you (@JonasSchaub ) and I should decide that.

So MIT or BSD?

**Comment by JonasSchaub** [comment]
> If "modify" does not include "extend", I think we're fine.

Yes, we should be totally fine, we just define all these as dependencies of the project and don't touch them.

> So MIT or BSD?

I vote for MIT, we are mostly using that licence in the group.

> I think you (@JonasSchaub ) and I should decide that.

Yes, we can decide that. But pro forma, all developers whose code has been previously published here under another licence, have to agree to the change. That is (according to Chris) why CDK never changed its licence later, even though they were not happy anymore with LGPL.

**Comment by FelixBaensch** [comment]
> I vote for MIT, we are mostly using that licence in the group.

Can you briefly explain this please, as I understand it the BSD license is even more open

> Yes, we can decide that. But pro forma, all developers whose code has been previously published here under another licence, have to agree to the change. That is (according to Chris) why CDK never changed its licence later, even though they were not happy anymore with LGPL.

How can this be organized? Could you mail everyone?

**Comment by JonasSchaub** [comment]
> Can you briefly explain this please, as I understand it the BSD license is even more open

Is it? Also depends on which BSD licence you're referring to, since there are multiple ones. For example, this BSD licence https://opensource.org/license/bsd-1-clause/ seems to be basically as permissive as MIT (https://choosealicense.com/licenses/mit/). And then MIT would have the advantages that we are already using it for other projects and that it is less complicated, i.e. there is only one.

This web page published by GitHub seems very helpful: https://choosealicense.com/licenses/ 

> How can this be organized? Could you mail everyone?

Yes, I will do that once we decided for one licence.

**Comment by FelixBaensch** [comment]
So then we should use MIT.

**Comment by JonasSchaub** [comment]
Great, I'll email to everyone!

**Comment by JonasSchaub** [comment]
- [ ] Felix
- [ ] Jonas
- [ ] Julian
- [ ] Samuel
- [ ] Betuel
- [ ] Max R

**Comment by JonasSchaub** [comment]
See #41
