### ISSUE TITLE
CH3 is parent fragment of CH4 when using Scaffold Generator

### ISSUE THREAD

**Issue by FelixBaensch** [FelixBaensch/MORTAR#87]
![image](https://github.com/FelixBaensch/MORTAR/assets/57186528/c374e8fe-310b-43ad-983e-cb7c45ac8246)

Scaffold Generator was applied to the attached test set (please remove the .txt extension) in default settings.
[ertl_alkenes.sdf.txt](https://github.com/FelixBaensch/MORTAR/files/15007959/ertl_alkenes.sdf.txt)

**Comment by JonasSchaub** [comment]
You imported without adding implicit hydrogens to open valences, correct? At first, I thought the issue was about all the open valences i the input mols.
And you set the Scaffold Generator Side chain setting to either "only side chains" or "scaffolds and side chains", correct?

In your SDF, the "CH3" input mol has a "3" set as the 6th property in its atom block. Does this define three explicit hydrogen atoms?

I'm guessing that the CH3 input mol gets saturated by Scaffold Generator into CH4. This looks weird at first glance but would actually be expected behaviour, in my opinion.

**Comment by FelixBaensch** [comment]
> You imported without adding implicit hydrogens to open valences, correct? At first, I thought the issue was about all the open valences i the input mols. And you set the Scaffold Generator Side chain setting to either "only side chains" or "scaffolds and side chains", correct?

Yes, the file was imported without adding implict hyrdogens. And the side chain setting was set to "scaffolds and side chains", so not quite default settings after all, sorry.
 
> In your SDF, the "CH3" input mol has a "3" set as the 6th property in its atom block. Does this define three explicit hydrogen atoms?

The 6th property in the atom block of a v2000 connection table stands for the valences. By default it is set to 0, which indicates the default valence.

> I'm guessing that the CH3 input mol gets saturated by Scaffold Generator into CH4. This looks weird at first glance but would actually be expected behaviour, in my opinion.

If you say so, and that reflects the desired behavior, feel free to close the issue. I opened it at your request.

**Comment by FelixBaensch** [comment]
For the sake of completeness:

![image](https://github.com/FelixBaensch/MORTAR/assets/57186528/c27d8734-fc60-418c-82c5-6f4ab7a300ae)

![image](https://github.com/FelixBaensch/MORTAR/assets/57186528/11141810-b774-44e3-b861-40ee737e60d5)
